.\" Copyright (C) 2014 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH cafe-keybinding-properties 1 "2014\-05\-02" "CAFE"
.SH NAME
\fBcafe-keybinding-properties \fP- configure CAFE keybindings
.SH SYNOPSIS
.B cafe-keybinding-properties
.RI [ OPTIONS...]
.SH DESCRIPTION
This executable is part of the package 'cafe\-control\-center': The CAFE Control Center.
.PP
The CAFE  keybindings preference tool enables you to display the default keyboard shortcuts
and customize them to your requirements.
.PP
You can also create hot keys. Hot keys  are
keyboard shortcuts that start applications or perform other useful actions.
.SH OPTIONS
This program accepts the standard CAFE and CTK options.
.SH AUTHORS
This manual page was writtenby Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
for the Debian project (but may be used by others).
.SH SEE ALSO
Latest version of the CAFE Desktop User Guide for your platform.
.PP
.BR "cafe-control-center" (1),
.BR "ctk-options" (7)
.PP
