##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:
  - ./debrepo-install

build_scripts:
  - ./build-debs

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/categories/preferences-desktop.png; fi
