##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-control-center
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - curl
    - desktop-file-utils
    - git
    - gla11y
    - gobject-introspection
    - intltool
    - libcanberra-gtk3-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmarco-dev
    - libcafe-desktop-dev
    - libcafe-menu-dev
    - libcafekbd-dev
    - libpango1.0-dev
    - librsvg2-bin
    - librsvg2-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxklavier-dev
    - libxml2-dev
    - libxrandr-dev
    - libxss-dev
    - libxt-dev
    - libpolkit-gobject-1-dev
    - make
    - cafe-common
    - cafe-settings-daemon-dev
    - python3-lxml
    - shared-mime-info
    - xsltproc
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/cafe-settings-daemon master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/categories/preferences-desktop.png; fi
